# 03 — Text Analysis & LLM-Based Annotation

This notebook uses the Anthropic API (Claude) to score each post on
linguistic and behavioral dimensions that cannot be captured by simple
statistics. Claude reads each Hebrew post and returns structured scores
that are then merged with the clean dataset for predictive modeling.

**Input:** `data/clean_posts.csv`
**Output:** `data/clean_posts_with_text.csv`

**Sections:**
1. Configuration & Setup
2. Load Data
3. Prompt Design & Single Post Test
4. Score All Posts (with incremental saving)
5. Manual Validation
6. Parse & Merge Results
7. Export

## 1. Configuration & Setup

In [1]:
import os
import json
import time
import pandas as pd
import numpy as np
from pathlib import Path
from dotenv import load_dotenv
import anthropic

# Load API key from .env file
load_dotenv()

# ── Paths ──────────────────────────────────────────────────────────────────
INPUT_FILE      = Path("../data/clean_posts.csv")
OUTPUT_FILE     = Path("../data/clean_posts_with_text.csv")
CHECKPOINT_FILE = Path("../data/text_scores_checkpoint.json")

# ── Model ──────────────────────────────────────────────────────────────────
MODEL      = "claude-haiku-4-5"
MAX_TOKENS = 600

# ── API client ─────────────────────────────────────────────────────────────
client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

print("✓ API client ready")
print(f"  Model:  {MODEL}")
print(f"  Input:  {INPUT_FILE}")
print(f"  Output: {OUTPUT_FILE}")

✓ API client ready
  Model:  claude-haiku-4-5
  Input:  ../data/clean_posts.csv
  Output: ../data/clean_posts_with_text.csv

## 2. Load Data

In [2]:
df = pd.read_csv(INPUT_FILE)

# Exclude Reels before any scoring
# Reels are video-first with minimal text — linguistic annotation
# is not meaningful for this format. They are kept in clean_posts.csv
# for behavioral EDA (02_eda.ipynb) but excluded here.
reels_excluded = (df['post_type'] == 'Reel').sum()
df = df[df['post_type'] != 'Reel'].copy()

print(f'Loaded {len(df) + reels_excluded} posts total')
print(f'Excluded {reels_excluded} Reels — {len(df)} posts for text analysis')
print()
df[['post_id', 'title', 'date', 'post_type', 'engagement_rate', 'view_through_rate']].head(3)

Loaded 97 posts total
Excluded 7 Reels — 90 posts for text analysis

,post_id,title,date,post_type,engagement_rate,view_through_rate
0,10234810932441995,חופשה עם ילדים זאת מעין חצי חופשה. \n\nלא מקבל...,2025-08-14,Photo,0.056085,0.834921
1,10238066919799644,מלחמה וסטרס עושות משהו מעניין לזמן.\n\nהן מותח...,2026-03-19,Photo,0.105033,0.947484
2,10237996040547707,מה אנחנו באמת רוצים כשאנחנו חושקים במישהו?\n\n...,2026-03-16,Photo,0.011610,0.918539

## 3. Prompt Design & Single Post Test

We first design the scoring prompt and test it on a single post
before running it on the full dataset. This lets us verify the
output format and scoring quality manually.

The prompt instructs Claude to:
- Read a Hebrew Facebook post
- Score it on 15 behavioral and linguistic dimensions
- Return scores as a valid JSON object only — no extra text

In [3]:
SYSTEM_PROMPT = """You are an expert in behavioral psychology and linguistic analysis.
You are analyzing Hebrew Facebook posts written by a single author — a behavioral
neuroscientist and published novelist — who uses social media to share personal
reflections and promote her book.

Your task is to score each post on the dimensions below.
Return ONLY a valid JSON object with no additional text, preamble, or markdown formatting.

Scoring dimensions:

1. emotional_valence: Overall emotional tone of the post
   1=very negative, 2=negative, 3=neutral, 4=positive, 5=very positive

2. emotional_intensity: How emotionally exposed and personally intense IS THE AUTHOR
   HERSELF in this post — not the emotional content of what she is describing, but her
   own emotional state as expressed. A post about a book character feeling something
   scores low even if the described emotion is strong.
   1: low — the author is observational or writing about something external.
      Little personal emotional exposure. Includes posts about others' experiences,
      book characters, or intellectual reflections.
   2: medium — the author expresses some personal feeling but it is moderate,
      present but not overwhelming.
   3: high — the author is raw, vulnerable, or intensely personally affected.
      The post could only have been written from a place of strong personal emotion.
      Examples: missing being pregnant, losing someone close, a deeply personal life moment.

3. tone: Primary tone of the post. Choose one:
   - reflective: personal experience, inner world, first-person emotional writing
   - recommendation: suggesting something to the audience (a book, series, idea, place)
   - book_accomplishment: announcing or celebrating something about the author's own book
   - occasion_anchored: the post is structured around a specific date or external event

4. marketing_mention: Does the post explicitly mention the book is available for purchase,
   name bookstores (סטימצקי, צומת ספרים, עברית), or include a direct call to buy?
   0=no, 1=yes

5. occasion_mention: Does the post reference a specific occasion such as
   ראש השנה, יום האישה, יום הולדת, חגים, מלחמה, or another named event?
   0=no, 1=yes

6. occasion_relevance: If occasion_mention=1, how central is the occasion to the post?
   1=passing mention only, 2=moderate role, 3=the post is primarily about the occasion
   If occasion_mention=0, return 0

7. dominant_pronoun: Which pronoun dominates the overall post body?
   - I: post is primarily first-person (אני, שלי, לי, אותי)
   - You: post primarily addresses the reader (את, אתה, אתם, שלך)
   - We: post uses collective voice (אנחנו, שלנו)
   - Mixed: no single pronoun dominates

8. opening_pronoun: What pronoun appears in the very first sentence?
   Options: I / You / We / None
   None = the first sentence does not clearly use any of these pronouns

9. question_presence: Does the post contain a direct question to the audience?
   0=no, 1=yes

10. list_structure: Is the post structured as a numbered or bullet list,
    or does it use clearly repeated parallel sentence structures?
    0=no, 1=yes

11. narrative_arc: Does the post tell a story with movement or change?
    1=no arc, observation or reflection only
    2=partial arc, some movement but no clear resolution
    3=clear arc with beginning, middle, and end or resolution

12. personal_vulnerability: How much does the author expose something
    genuinely private, risky, or emotionally difficult about herself?

    1 = surface level — the author shares feelings or opinions but nothing
        that feels risky or exposing. Includes emotional posts about external
        topics (the book, other people, events, ideas). The author could have
        written this without feeling personally exposed.

    2 = moderately personal — the author reveals something genuinely private
        but maintains some distance or wraps it in narrative.

    3 = highly vulnerable — the author exposes something intimate, difficult,
        or emotionally raw that most people would hesitate to share publicly.
        The post could only have been written from a place of real courage.

    Key distinction: emotion about external subjects does NOT equal vulnerability.
    A post expressing strong feelings about a book character scores 1.
    A post admitting fear, failure, grief, or a deeply personal life moment scores 3.

13. parenthood_theme: Is parenthood, motherhood, or the author's
    children a meaningful theme in this post?
    0 = not mentioned, or only a passing reference
    1 = children or parenthood play a meaningful role in the post

14. shared_context: Does the post tap into either a major external event
    happening simultaneously, or a significant shared life experience that
    a large portion of the audience has lived through?
    Use the post date provided to judge relevance for external events.

    1 = yes, when the post connects to:
        - A concrete external event happening simultaneously: war, military
          conflict, Jewish holidays, summer vacation season, national news,
          back to school period — even if not explicitly named in the text
        - A major shared life experience tied to a specific life stage:
          pregnancy, new parenthood, loss of a parent, immigration,
          school experiences, marriage, divorce

    0 = no, when:
        - The content is purely personal and idiosyncratic
        - The feeling is universal but not tied to a specific life stage
          or external event (general loneliness, happiness, love)
        - The emotion is relatable but not situationally shared
        - Community or niche events do NOT qualify — book signings,
          literary gatherings, or audience-specific cultural moments
          require broad societal or universal life stage relevance,
          not niche audience affinity

    Key distinction: shared feelings alone do NOT qualify.
    "Missing being pregnant" scores 1 — specific shared life transition.
    "Feeling sad today" scores 0 — universal emotion with no shared context.
    "Attending a book signing" scores 0 — niche community event.
    A post about war anxiety scores 1 even if the word war is not mentioned.

15. tag_count_people: How many individual people are tagged in this post?
    Tagged people appear as proper names (first + last name) WITHOUT @ symbol.
    Look for names at the END in a credits section, mid-post when crediting someone,
    in Latin (e.g. "Kedem Diamant") or Hebrew (e.g. "ליאור שרף") script.
    Be inclusive — if it looks like a person's name being credited, count it.
    Return an integer: 0, 1, 2, 3, etc.

16. explanation: A brief 2-3 sentence explanation of your scores,
    focusing on the dimensions that were most ambiguous or interesting.
    Write in English.

Return your response as a single JSON object with exactly these keys:
emotional_valence, emotional_intensity, tone, marketing_mention,
occasion_mention, occasion_relevance, dominant_pronoun, opening_pronoun,
question_presence, list_structure, narrative_arc, personal_vulnerability,
parenthood_theme, shared_context, tag_count_people, explanation
"""

In [4]:
def score_post(post_text, post_date=None):
    """Send a single post to Claude and return the parsed JSON scores."""
    date_line = f"Post date: {post_date}\n\n" if post_date else ""
    message = client.messages.create(
        model=MODEL,
        max_tokens=MAX_TOKENS,
        system=SYSTEM_PROMPT,
        messages=[
            {
                "role": "user",
                "content": f"Please score the following Hebrew Facebook post:\n\n{date_line}Post text:\n{post_text}"
            }
        ]
    )

    raw = message.content[0].text.strip()

    # Strip markdown code fences if present
    if raw.startswith("```"):
        raw = raw.split("\n", 1)[1]
        raw = raw.rsplit("```", 1)[0].strip()

    return json.loads(raw)

In [85]:
# ── Single post test ────────────────────────────────────────────────────────
# Test on the first post in the dataset
test_post = df.iloc[0]

print("POST TEXT:")
print("─" * 60)
print(test_post["title"])
print("─" * 60)
print(f"Date: {test_post['date']}  |  Type: {test_post['post_type']}")
print(f"Engagement rate: {test_post['engagement_rate']:.3f}  |  VTR: {test_post['view_through_rate']:.3f}")
print()

# Score it
result = score_post(test_post["title"], post_date=test_post["date"])

print("CLAUDE'S SCORES:")
print("─" * 60)
for key, value in result.items():
    if key != "explanation":
        print(f"  {key:<25} {value}")
print()
print("EXPLANATION:")
print(result.get("explanation", "No explanation provided"))

POST TEXT:
────────────────────────────────────────────────────────────
חופשה עם ילדים זאת מעין חצי חופשה.

לא מקבלים באמת את כל החופש שהיית רוצה ורוב הזמן את די עובדת, אבל כן יש רגעים קסומים.

כשדניאל קופץ וצוחק בבריכה. כשאני רואה איך לאט לאט נבנה לו הביטחון והוא לא מפחד יותר להיכנס ואפילו רוצה לקפוץ. כשאנחנו מלמדים אותו מזה קייט ופתאום הוא מחפש קייטים בים.

כשאני מביטה בקפלים המתוקים שברגליים השמנמנות שלו ומנסה לשתות כל רגע כזה לפני שהוא פשוט חולף.

כי למרות שכל ארוחה במסעדה היא סימפוניה של ״אני רוצה גם״ וכל נסיעה לים יכולה להסתיים בטנטרום כשרוצים כבר ללכת, אני כל הזמן מזכירה לעצמי שזה עוד רגע עובר והם כבר יהיו גדולים ואולי כבר לא יצטרכו אותי כל-כך.

כי הזמן יש בו משהו מתעתע. הוא נראה כאילו לעולם לא יגמר כשהוא בהתקף טנטרום אבל אז בן רגע הוא פתאם נהיה גדול וכבר לא התינוק הקטן והשמנמן שהחזקתי בידיים לפני רגע.

אז זאת מעין חצי חופשה כזאת שדורשת יותר עבודה סביב הילד אבל גם ממלאת אותי בו.

בתמונה - כלי הנשק הסודי שלי, גלידה.
────────────────────────────────────────────────────────────
Date: 2025-08-14  |  Type: Photo
Engagement rate: 0.056  |  VTR: 0.835

CLAUDE'S SCORES:
────────────────────────────────────────────────────────────
  emotional_valence         4
  emotional_intensity       3
  tone                      reflective
  marketing_mention         0
  occasion_mention          1
  occasion_relevance        2
  dominant_pronoun          I
  opening_pronoun           None
  question_presence         0
  list_structure            0
  narrative_arc             2
  personal_vulnerability    3
  parenthood_theme          1
  shared_context            1
  tag_count_people          0

EXPLANATION:
This is a deeply personal reflection on motherhood and the passage of time, written with raw vulnerability about the bittersweet nature of parenting young children during summer break. The author exposes genuine fears about her children growing up and her changing role as a mother, creating an intimate moment that goes beyond surface emotion. The post taps into the shared experience of parenthood and summer vacation season, with summer embodied through concrete moments at pools and beaches.

**Manual check:** Read the post above and verify the scores make sense.
If something looks wrong, adjust the prompt in the cell above and re-run the test
before proceeding to score all posts.

## 4. Score All Posts (with incremental saving)

We score all posts one by one, saving results to a checkpoint file after
each post. If the process is interrupted, re-running this cell will skip
already-scored posts and continue from where it left off.

In [5]:
# Load existing checkpoint if available
if CHECKPOINT_FILE.exists():
    with open(CHECKPOINT_FILE, "r", encoding="utf-8") as f:
        checkpoint = json.load(f)
    print(f"Loaded checkpoint: {len(checkpoint)} posts already scored")
else:
    checkpoint = {}
    print("No checkpoint found — starting fresh")

# Score all posts
errors = []
total  = len(df)

for _, row in df.iterrows():
    post_id = str(row["post_id"])

    # Skip if already scored
    if post_id in checkpoint:
        continue

    # Skip posts with no text
    if pd.isna(row["title"]) or str(row["title"]).strip() == "":
        errors.append({"post_id": post_id, "error": "empty title"})
        continue

    try:
        scores = score_post(row["title"], post_date=row["date"])
        checkpoint[post_id] = scores

        # Save checkpoint after every post
        with open(CHECKPOINT_FILE, "w", encoding="utf-8") as f:
            json.dump(checkpoint, f, ensure_ascii=False, indent=2)

        print(f"✓ [{len(checkpoint)}/{total}] post_id {post_id} — tone: {scores.get('tone')} | valence: {scores.get('emotional_valence')}")

        # Small delay to avoid rate limiting
        time.sleep(0.5)

    except Exception as e:
        print(f"✗ [{len(checkpoint)}/{total}] post_id {post_id} — ERROR: {e}")
        errors.append({"post_id": post_id, "error": str(e)})

print()
print(f"Done. {len(checkpoint)} posts scored, {len(errors)} errors.")
if errors:
    print("Errors:")
    for e in errors:
        print(f"  post_id {e['post_id']}: {e['error']}")

No checkpoint found — starting fresh
✓ [1/90] post_id 10234810932441995 — tone: reflective | valence: 4
✓ [2/90] post_id 10238066919799644 — tone: reflective | valence: 4
✓ [3/90] post_id 10237996040547707 — tone: recommendation | valence: 4
✓ [4/90] post_id 10237942817737170 — tone: book_accomplishment | valence: 4
✓ [5/90] post_id 10237913037112673 — tone: book_accomplishment | valence: 5
✓ [6/90] post_id 10237860987931476 — tone: book_accomplishment | valence: 4
✓ [7/90] post_id 10237836439037769 — tone: reflective | valence: 4
✓ [8/90] post_id 10237816770946079 — tone: reflective | valence: 4
✓ [9/90] post_id 10237734887059033 — tone: reflective | valence: 4
✓ [10/90] post_id 10237705072153679 — tone: book_accomplishment | valence: 4
✓ [11/90] post_id 10237651650578173 — tone: book_accomplishment | valence: 4
✓ [12/90] post_id 10237628211152202 — tone: reflective | valence: 4
✓ [13/90] post_id 10237613761070959 — tone: book_accomplishment | valence: 4
✓ [14/90] post_id 10237589063333531 — tone: reflective | valence: 4
✓ [15/90] post_id 10237515737620434 — tone: reflective | valence: 5
✓ [16/90] post_id 10237444469638779 — tone: reflective | valence: 4
✓ [17/90] post_id 10237417133115383 — tone: book_accomplishment | valence: 4
✓ [18/90] post_id 10237354197822040 — tone: book_accomplishment | valence: 5
✓ [19/90] post_id 10237327327070288 — tone: reflective | valence: 4
✓ [20/90] post_id 10237294154000982 — tone: reflective | valence: 4
✓ [21/90] post_id 10237233711489957 — tone: reflective | valence: 4
✓ [22/90] post_id 10237199938245647 — tone: book_accomplishment | valence: 5
✓ [23/90] post_id 10237165323100290 — tone: reflective | valence: 4
✓ [24/90] post_id 10237146470828995 — tone: recommendation | valence: 5
✓ [25/90] post_id 10237120337615681 — tone: reflective | valence: 4
✓ [26/90] post_id 10237073544925893 — tone: book_accomplishment | valence: 5
✓ [27/90] post_id 10237042036378199 — tone: recommendation | valence: 5
✓ [28/90] post_id 10237021599027278 — tone: book_accomplishment | valence: 4
✓ [29/90] post_id 10236976374536694 — tone: reflective | valence: 4
✓ [30/90] post_id 10236956000907366 — tone: reflective | valence: 4
✓ [31/90] post_id 10236871700119899 — tone: reflective | valence: 4
✓ [32/90] post_id 10236852449758652 — tone: book_accomplishment | valence: 4
✓ [33/90] post_id 10236823927405611 — tone: book_accomplishment | valence: 5
✓ [34/90] post_id 10236799038903414 — tone: book_accomplishment | valence: 5
✓ [35/90] post_id 10236787524495561 — tone: reflective | valence: 4
✓ [36/90] post_id 10236754736115872 — tone: book_accomplishment | valence: 5
✓ [37/90] post_id 10236732023268065 — tone: reflective | valence: 4
✓ [38/90] post_id 10236685673469349 — tone: book_accomplishment | valence: 5
✓ [39/90] post_id 10236659719340512 — tone: reflective | valence: 3
✓ [40/90] post_id 10236608423258142 — tone: reflective | valence: 4
✓ [41/90] post_id 10236531633458445 — tone: reflective | valence: 4
✓ [42/90] post_id 10236476555721536 — tone: book_accomplishment | valence: 5
✓ [43/90] post_id 10236436203632759 — tone: reflective | valence: 4
✓ [44/90] post_id 10236378927880901 — tone: recommendation | valence: 4
✓ [45/90] post_id 10236344825428361 — tone: reflective | valence: 4
✓ [46/90] post_id 10236300497160182 — tone: book_accomplishment | valence: 5
✓ [47/90] post_id 10236260725365912 — tone: reflective | valence: 3
✓ [48/90] post_id 10236200714425676 — tone: reflective | valence: 4
✓ [49/90] post_id 10236154312145648 — tone: recommendation | valence: 4
✓ [50/90] post_id 10236114993602709 — tone: recommendation | valence: 4
✓ [51/90] post_id 10236087914965760 — tone: book_accomplishment | valence: 4
✓ [52/90] post_id 10236061097975352 — tone: reflective | valence: 4
✓ [53/90] post_id 10235992412458257 — tone: book_accomplishment | valence: 5
✓ [54/90] post_id 10235979005163083 — tone: reflective | valence: 4
✓ [55/90] post_id 10235964677004888 — tone: reflective | valence: 4
✓ [56/90] post_id 10235905122196055 — tone: reflective | valence: 5
✓ [57/90] post_id 10235889728531223 — tone: book_accomplishment | valence: 4
✓ [58/90] post_id 10235862427448713 — tone: reflective | valence: 4
✓ [59/90] post_id 10235809856614475 — tone: reflective | valence: 5
✓ [60/90] post_id 10235769329681327 — tone: reflective | valence: 3
✓ [61/90] post_id 10235718145401752 — tone: reflective | valence: 4
✓ [62/90] post_id 10235679656559555 — tone: recommendation | valence: 4
✓ [63/90] post_id 10235666649074376 — tone: book_accomplishment | valence: 5
✓ [64/90] post_id 10235641937536603 — tone: book_accomplishment | valence: 5
✓ [65/90] post_id 10235589190017948 — tone: reflective | valence: 4
✓ [66/90] post_id 10235545113356059 — tone: recommendation | valence: 5
✓ [67/90] post_id 10235356098350802 — tone: book_accomplishment | valence: 5
✓ [68/90] post_id 10235322834119217 — tone: reflective | valence: 4
✓ [69/90] post_id 10235294652694699 — tone: reflective | valence: 5
✓ [70/90] post_id 10235269919796392 — tone: recommendation | valence: 4
✓ [71/90] post_id 10235255835284288 — tone: book_accomplishment | valence: 4
✓ [72/90] post_id 10235243382892986 — tone: book_accomplishment | valence: 5
✓ [73/90] post_id 10235230954062273 — tone: reflective | valence: 4
✓ [74/90] post_id 10235203918906411 — tone: reflective | valence: 4
✓ [75/90] post_id 10235152812908793 — tone: book_accomplishment | valence: 5
✓ [76/90] post_id 10235140355037354 — tone: book_accomplishment | valence: 5
✓ [77/90] post_id 10235127285750630 — tone: book_accomplishment | valence: 5
✓ [78/90] post_id 10235114414068846 — tone: book_accomplishment | valence: 4
✓ [79/90] post_id 10235065698890997 — tone: book_accomplishment | valence: 5
✓ [80/90] post_id 10235051703501121 — tone: book_accomplishment | valence: 4
✓ [81/90] post_id 10234961749012315 — tone: reflective | valence: 4
✓ [82/90] post_id 10234898611833925 — tone: book_accomplishment | valence: 4
✓ [83/90] post_id 10234873110996420 — tone: reflective | valence: 4
✓ [84/90] post_id 10234270464250628 — tone: reflective | valence: 4
✓ [85/90] post_id 10234424434779795 — tone: reflective | valence: 3
✓ [86/90] post_id 10234539068365563 — tone: reflective | valence: 4
✓ [87/90] post_id 10234628050590063 — tone: reflective | valence: 4
✓ [88/90] post_id 10234689050595025 — tone: reflective | valence: 4
✓ [89/90] post_id 10234725831154516 — tone: reflective | valence: 4
✓ [90/90] post_id 10233794188824040 — tone: reflective | valence: 4

Done. 90 posts scored, 0 errors.

### Detect Missing Dimensions

When new scoring dimensions are added after some posts have already been scored,
existing checkpoint entries won't have those dimensions. This cell identifies
which posts are missing any of the expected dimensions and marks them for re-scoring.

Re-running the scoring loop below will then re-score only those posts.

In [6]:
# All dimensions we expect in every scored post
EXPECTED_DIMS = [
    "emotional_valence", "emotional_intensity", "tone",
    "marketing_mention", "occasion_mention", "occasion_relevance",
    "dominant_pronoun", "opening_pronoun", "question_presence",
    "list_structure", "narrative_arc", "personal_vulnerability",
    "parenthood_theme", "shared_context", "tag_count_people", "explanation"
]

# Find posts missing any expected dimension
incomplete = [
    post_id for post_id, scores in checkpoint.items()
    if any(dim not in scores for dim in EXPECTED_DIMS)
]

if incomplete:
    print(f"Found {len(incomplete)} post(s) missing one or more dimensions:")
    for post_id in incomplete:
        missing = [d for d in EXPECTED_DIMS if d not in checkpoint[post_id]]
        print(f"  post_id {post_id} — missing: {missing}")
    print()
    print("Removing incomplete entries from checkpoint so they get re-scored...")
    for post_id in incomplete:
        del checkpoint[post_id]
    print(f"Checkpoint now has {len(checkpoint)} complete entries.")
    print("Re-run the scoring loop below to fill in the missing posts.")
else:
    print(f"All {len(checkpoint)} checkpoint entries have the expected dimensions. Nothing to re-score.")

All 90 checkpoint entries have the expected dimensions. Nothing to re-score.

## 5. Manual Validation

Before merging scores into the dataset, manually inspect a sample of posts
to verify that Claude's scores match your intuition as the author.

This is an important methodological step — it establishes that the annotation
is valid before using it in any predictive model.

In [7]:
# Display a random sample of 5 posts with their scores for manual validation
sample = df.sample(5, random_state=42)

for _, row in sample.iterrows():
    post_id = str(row["post_id"])
    scores  = checkpoint.get(post_id, {})

    print("=" * 65)
    print(f"POST ID: {post_id}  |  Date: {row['date']}  |  Type: {row['post_type']}")
    print(f"Engagement rate: {row['engagement_rate']:.3f}  |  VTR: {row.get('view_through_rate', 'N/A')}  |  Category: {row['post_category']}")
    print()

    # Structural features
    print("STRUCTURAL FEATURES:")
    print(f"  has_hashtag:       {row.get('has_hashtag', 'N/A')}  |  hashtag_count: {row.get('hashtag_count', 'N/A')}")
    print(f"  mentions_children: {row.get('mentions_children', 'N/A')}")
    print()

    # Full post text
    print("FULL TEXT:")
    print(str(row["title"]))
    print()

    # LLM scores
    print("LLM SCORES:")
    for key, value in scores.items():
        if key != "explanation":
            print(f"  {key:<25} {value}")
    print()
    print("EXPLANATION:")
    print(scores.get("explanation", "N/A"))
    print()

=================================================================
POST ID: 10236531633458445  |  Date: 2025-12-07  |  Type: Photo
Engagement rate: 0.085  |  VTR: 0.7819548872180451  |  Category: Viral

STRUCTURAL FEATURES:
  has_hashtag:       1  |  hashtag_count: 1
  mentions_children: 0

FULL TEXT:
#אנשי_הגם_וגם

האלטר אגו שלי הוא שחקנית.

הייתי במגמת תיאטרון בתיכון, יחד עם ביולוגיה (כמובן).

וכשהייתי בתואר השני בירושלים, הלכתי לחוג תיאטרון. פעם בשבוע.
שנתיים ברצף.

ובסוף כל שנה, העלנו הצגה. איכשהו בכל פעם זו הייתה הצגה של חנוך לוין.

ואולי זה לא היה במקרה, כי אני אכן מרגישה הזדהות עמוקה עם הדרך שבה הוא מתאר בדידות וכאב ורצון להיות נאהב ולהשתייך ביצירות שלו.ֿ

בהצגה האחרונה שלנו, ״קרום״, שיחקתי את פליציה. דמות שהיא בודדה בפנים ודורכת על אחרים בניסיון שיראו ויאהבו אותה. יש משהו משחרר בלשחק דמויות כאלה קיצוניות. משהו שמאפשר לגעת באזורים בנפש שאסור לגעת בהם ביומיום.

אחד הדוקטורנטים שעבדתי איתו במעבדה, אמר לי שיום אחד לא אוכל לעשות את זה - ללכת לחוג תיאטרון פעם בשבוע ועוד לעלות הצגה בסוף שנה. אצטרך להתמקד, לבחור במשהו אחד, כלומר במחקר. להיות רצינית בו אם אני רוצה להצליח. אז, חשבתי שאולי הוא צודק.

היום אני מבינה שזה תלוי איך מגדירים הצלחה.

באקדמיה בתחום שלי - מדעי המוח ובהרבה תחומים אחרים יש נטייה לקשר הצלחה למומחיות. להפוך למומחה הגדול בתחומך, לחפור כמו בולדוזר לעומק של התחום עד שמגיעים לשורשים העמוקים ביותר.

וזה אכן מרשים, אבל יש לזה מחיר - הרבה פעמים נמצא את עצמינו בתחתית של באר, השאלות הולכות ומתרחקות מהחיים על פני השטח וכמות האנשים שמבינים על מה את בכלל מדברת הולכת ומצטמצמת.

אני רואה ביכולת להחזיק בעוד תחום, גם אם זה רק חלקית, הצלחה. ביכולת רגע להיכנס לנעליים אחרות, לתת לעוד חלקים בך ביטוי, להרחיב את העשייה ואת המגע עם אנשים במקום לצמצם.

המשכתי להחזיק כל פעם בתחום כזה, בתחביב כזה שאימצתי בצורה רצינית למדי. בהמשך זה הפך להיות אימפרוביזציה ואחר-כך כתיבה.

יש מאין ״כוח״ כזה שאני מרגישה כשאני מחזיקה בעוד יכולת, עוד ידע שהוא מעבר לידע ולמומחיות של התחום העיקרי שבו אני עוסקת, כאילו אני מחזיקה מאין סוד כזה שמאפשר לי עוד צורת הסתכלות על העולם. אבל מעבר לזה, אני נותנת מענה לעוד חלקים בנפש שלי - האומנית שבי.

אז אני עדיין לא תמיד מצליחה לשלב את המחקר והאומנות ולפעמים הם נתיבים לגמרי נפרדים בחיי וכמו שסיפרתי פה כמה פעמים - יש לזה מחיר. ללא לחפור ולהעמיק בתחומך בצורה שתתן לך גם כוח וקשרים.

ועם זאת, אני לא רואה את עצמי עוסקת רק באחד מהם. הצלחה עבורי היא להצליח לשלב את שניהם בחיי.

בתמונה - אני בתור פליציה.

LLM SCORES:
  emotional_valence         4
  emotional_intensity       3
  tone                      reflective
  marketing_mention         0
  occasion_mention          0
  occasion_relevance        0
  dominant_pronoun          I
  opening_pronoun           None
  question_presence         0
  list_structure            0
  narrative_arc             3
  personal_vulnerability    3
  parenthood_theme          0
  shared_context            1
  tag_count_people          0

EXPLANATION:
This is a deeply personal, introspective post where the author reflects on her dual identity as both a neuroscientist and artist, revealing the tension and resolution in how she defines success. The post achieves high emotional intensity and vulnerability through raw exposure of internal conflict—admitting doubt, the pressure to specialize, and her hard-won decision to reject traditional academic definitions of success in favor of integration. The narrative arc moves from past (theater in high school and graduate school) through present conflict (the doctorate student's pressure to choose) to resolution (redefining success as synthesis rather than expertise). This connects to the shared context of identity negotiation across multiple life domains, a meaningful life-stage experience many face when building careers and pursuing multiple callings.

=================================================================
POST ID: 10237165323100290  |  Date: 2026-01-22  |  Type: Photo
Engagement rate: 0.075  |  VTR: 0.783710407239819  |  Category: Viral

STRUCTURAL FEATURES:
  has_hashtag:       1  |  hashtag_count: 1
  mentions_children: 1

FULL TEXT:
הייתי כל-כך הרבה זמן בהיריון ששכחתי כבר מה זה לא להיות בהיריון.

מזה להכיר את הגבולות של עצמי, של הגוף שלי, כמה אני יכולה וכמה לא, מבלי שיש מישהו אחר שם בפנים שצריך לשמור עליו.

שנה אחרי הלידה השנייה, נזכרתי שכשזאת רק אני, הציפייה שלי מעצמי היא אגרסיבית. להיות הכל בו-זמנית, להיות בכל מקום ולהצליח בהכל.

כשהייתי ילדה, אמא שלי תמיד הייתה מספרת לי על איזו קרובת משפחה או בת של חברים (אצל רוסים אין באמת כזה הבדל), שהיא גם רופאה וגם נשואה לאיזה מהנדס מוצלח וגם ילדה כבר את הילד השלישי. שהיא גם וגם וגם…

ואני גדלתי בהבנה שכדי שיראו אותי, אני צריכה להיות הגם וגם הזה, ולא רק להיות אלא להביא הוכחות. להביא את התעודות, הפרסים והמדליות.

בלעדיהם, לפי ההבנה שלי אז, לא הייתה לי משמעות.

עד שנכנסתי להיריון. ושם, הייתה לי משמעות גם בלי כל התארים וההצלחות. הייתה משמעות רק לקיום עצמו שלי (בתוספת ההיריון כמובן).

שם פתאם למדתי להקל על עצמי,
לא ללכת לעוד אימון בערב למרות שחזרתי מאוחר מהעבודה,
לא להישאר עד השעות הקטנות של הלילה בעבודה,
לא להיות בעשייה כל דקה מהיום, והדבר הכי חשוב -
למדתי לנוח, שזה בסדר לשבת על הספה ולצפות במשהו בנטפליקס או לקרוא ספר במיטה ככה באמצע היום.
כי היה את היצור היקר הזה שגדל לי בבטן שרציתי לשמור עליו (ולא שמתי-לב שבעצם הוא מלמד אותי לשמור על עצמי).

לקח לי הרבה שנים ושני ילדים כדי להבין שהתייחסתי לעצמי באופן נורא. שהייתי ביקורתית ושיפוטית ושלא אהבתי את עצמי ללא תנאי.
ההבנה הזאת היא כואבת. כי את מבינה שהאדם שהיה אמור להתייחס אליך הכי טוב, התייחס אלייך באופן נורא.
אפשר להגיד שיש לזה עוד צד, שאפתני שבאמת מגיע למצוינות,
שסיימתי דוקטורט, שהתקבלתי לעבודה טובה, שהצלחתי לכתוב ולהוציא (פאקינג) ספר! ושאפילו התקבלתי לתוכנית במשכנות שאננים. וגם לחזור למשקל של לפני הלידות.

ועדיין, אני מרגישה צורך לבקש מעצמי סליחה. סליחה על כל הפעמים שדיברתי לא יפה, שלא התייחסתי למתי שהייתי עייפה ובקצה גבול היכולת שלי, שלא חמלתי אותי ושלא חיבקתי אותי מספיק ושלא הזכרתי לעצמי בכל רגע שאני ראויה ושווה גם בלי כל ההצלחות האלה, וגם שכל הכשלונות שהיו לי - הם לא אומרים עליי כלום. רק שדרכתי במקום הלא נכון ויש מקום אחר שמחכה לי.

והיום, שני הבנים שלי מלמדים אותי לאהוב. כי כשאני נתקלת בשאלה או התלבטות בחיים שלי, אני מדמיינת את דניאל או נועם ניגשים אליי בבגרותם ומתייעצים איתי ואת אותה תשובה שאני עונה להם, אני יודעת היום לענות לעצמי. וברוב הפעמים זאת לא אותה התשובה שהייתי נותנת לעצמי פעם. אז אני רק מקווה שהפער הזה ילך ויצטמצם גם בלי צורך בהיריון נוסף בשנים הקרובות.

בתמונה - הדרך שלי להירגע, שמש, ים וקייט.

#אנשי_הגם_וגם

LLM SCORES:
  emotional_valence         4
  emotional_intensity       3
  tone                      reflective
  marketing_mention         0
  occasion_mention          0
  occasion_relevance        0
  dominant_pronoun          I
  opening_pronoun           I
  question_presence         0
  list_structure            1
  narrative_arc             3
  personal_vulnerability    3
  parenthood_theme          1
  shared_context            1
  tag_count_people          2

EXPLANATION:
This is a deeply vulnerable post where the author traces her journey from childhood perfectionism through pregnancy and motherhood to self-compassion. The narrative arc is clear: childhood conditioning → realization through pregnancy → two children later, painful recognition of self-criticism → gradual learning to love herself through her sons. The vulnerability is extremely high—she exposes her harshest self-judgments, the pain of realizing she was unkind to herself, and her ongoing struggle to internalize self-worth independent of achievement. The post taps into the shared life experience of motherhood and the universal transition of learning to value oneself beyond accomplishments, though it's also deeply idiosyncratic. Daniel and Noam (her sons) are named in the text as meaningful figures in her healing.

=================================================================
POST ID: 10235905122196055  |  Date: 2025-10-22  |  Type: Photo
Engagement rate: 0.065  |  VTR: 0.8571428571428571  |  Category: Algorithm Pushed

STRUCTURAL FEATURES:
  has_hashtag:       1  |  hashtag_count: 1
  mentions_children: 0

FULL TEXT:
איזה כיף זה חברות.

כאלה שאת יכולה לשבת איתן בבר ולרגע כל העולם נעלם. רק אתן קיימות.

ממלאות את עצמכן אחת בשנייה, אלכוהול, פיצה ומילים והרבה הרבה צחוק. אתן צוחקות מדברים שאף-אחד אחר לא מבין אבל אתכן זה מצחיק ללא שליטה.

מבינות אחת את השנייה במבט. לא באמת צריכות להגיד יותר מדי.

גם לאלי, גיבורת #בין_המסדרונות יש חברות כאלה, ובמיוחד אחת שנשארת איתה גם בחייה הבוגרים, מאיה. היחסים ביניהן אמנם עוברים עליות ומורדות, אבל ההבנה הזאת ללא צורך במילים היא זאת שהופכת את החברות לעוגן, לבית, למקום שתמיד רוצים לחזור אליו.

בתמונה - ערב שהסתיים עם 2.5 קוקטיילים וצ׳ייסר והאנגאובר למחרת.

LLM SCORES:
  emotional_valence         5
  emotional_intensity       2
  tone                      reflective
  marketing_mention         0
  occasion_mention          0
  occasion_relevance        0
  dominant_pronoun          You
  opening_pronoun           None
  question_presence         0
  list_structure            0
  narrative_arc             1
  personal_vulnerability    1
  parenthood_theme          0
  shared_context            0
  tag_count_people          1

EXPLANATION:
The post celebrates friendship with genuine warmth and positive emotion (valence 5), but the author maintains observational distance by primarily addressing 'you' (the friend) rather than exposing her own inner emotional state. While the writing celebrates intimacy between friends, the author herself remains somewhat protected behind the celebration of the concept—this is appreciation of friendship rather than personal vulnerability. The post transitions to her character Maya from her book, grounding it more in narrative reflection than raw personal exposure.

=================================================================
POST ID: 10235255835284288  |  Date: 2025-09-18  |  Type: Content
Engagement rate: 0.078  |  VTR: 0.8475836431226765  |  Category: Audience Favorite

STRUCTURAL FEATURES:
  has_hashtag:       0  |  hashtag_count: 0
  mentions_children: 0

FULL TEXT:
יש סקירות שעושות ‘קוואץ’ כזה בלב - זו אחת מהן.

תודה Hadar Azoulay Liberman על הסקירה הנהדרת שלך:)

LLM SCORES:
  emotional_valence         4
  emotional_intensity       2
  tone                      book_accomplishment
  marketing_mention         0
  occasion_mention          0
  occasion_relevance        0
  dominant_pronoun          Mixed
  opening_pronoun           None
  question_presence         0
  list_structure            0
  narrative_arc             1
  personal_vulnerability    1
  parenthood_theme          0
  shared_context            0
  tag_count_people          1

EXPLANATION:
The post celebrates a positive book review with a warm but brief expression of gratitude. The author expresses personal pleasure (the 'kvatz in the heart' metaphor) but maintains moderate emotional intensity—this is a public acknowledgment rather than a deeply felt or vulnerable disclosure. The dominant tone is book_accomplishment, celebrating external recognition of her work.

=================================================================
POST ID: 10234810932441995  |  Date: 2025-08-14  |  Type: Photo
Engagement rate: 0.056  |  VTR: 0.834920634920635  |  Category: Algorithm Pushed

STRUCTURAL FEATURES:
  has_hashtag:       0  |  hashtag_count: 0
  mentions_children: 1

FULL TEXT:
חופשה עם ילדים זאת מעין חצי חופשה.

לא מקבלים באמת את כל החופש שהיית רוצה ורוב הזמן את די עובדת, אבל כן יש רגעים קסומים.

כשדניאל קופץ וצוחק בבריכה. כשאני רואה איך לאט לאט נבנה לו הביטחון והוא לא מפחד יותר להיכנס ואפילו רוצה לקפוץ. כשאנחנו מלמדים אותו מזה קייט ופתאום הוא מחפש קייטים בים.

כשאני מביטה בקפלים המתוקים שברגליים השמנמנות שלו ומנסה לשתות כל רגע כזה לפני שהוא פשוט חולף.

כי למרות שכל ארוחה במסעדה היא סימפוניה של ״אני רוצה גם״ וכל נסיעה לים יכולה להסתיים בטנטרום כשרוצים כבר ללכת, אני כל הזמן מזכירה לעצמי שזה עוד רגע עובר והם כבר יהיו גדולים ואולי כבר לא יצטרכו אותי כל-כך.

כי הזמן יש בו משהו מתעתע. הוא נראה כאילו לעולם לא יגמר כשהוא בהתקף טנטרום אבל אז בן רגע הוא פתאם נהיה גדול וכבר לא התינוק הקטן והשמנמן שהחזקתי בידיים לפני רגע.

אז זאת מעין חצי חופשה כזאת שדורשת יותר עבודה סביב הילד אבל גם ממלאת אותי בו.

בתמונה - כלי הנשק הסודי שלי, גלידה.

LLM SCORES:
  emotional_valence         4
  emotional_intensity       3
  tone                      reflective
  marketing_mention         0
  occasion_mention          1
  occasion_relevance        2
  dominant_pronoun          I
  opening_pronoun           None
  question_presence         0
  list_structure            0
  narrative_arc             2
  personal_vulnerability    3
  parenthood_theme          1
  shared_context            1
  tag_count_people          0

EXPLANATION:
This is a deeply vulnerable post where the author exposes the raw emotional complexity of motherhood—the tension between exhaustion and the ache of time passing too quickly. The post is anchored to summer vacation (occasion) but transcends it into a meditation on mortality and maternal ambivalence. The author's intense first-person emotional exposure, specific physical memories (dimples on Daniel's legs), and admission of her own mortality fears demonstrate genuine courage in sharing something most mothers feel but rarely articulate publicly.

In [89]:
# Look up a specific post by index (change the number to inspect any post)
INSPECT_INDEX = 0  # ← change this to inspect a different post

row     = df.iloc[INSPECT_INDEX]
post_id = str(row["post_id"])
scores  = checkpoint.get(post_id, {})

print("=" * 65)
print(f"POST ID: {post_id}  |  Date: {row['date']}  |  Type: {row['post_type']}")
print(f"Engagement rate: {row['engagement_rate']:.3f}  |  VTR: {row.get('view_through_rate', 'N/A')}  |  Category: {row['post_category']}")
print()

# Structural features
print("STRUCTURAL FEATURES:")
print(f"  has_hashtag:       {row.get('has_hashtag', 'N/A')}  |  hashtag_count: {row.get('hashtag_count', 'N/A')}")
print(f"  has_tag:           {row.get('has_tag', 'N/A')}")
print(f"  mentions_children: {row.get('mentions_children', 'N/A')}")
print()

# Full post text
print("FULL TEXT:")
print(row["title"])
print()

# LLM scores
print("LLM SCORES:")
for key, value in scores.items():
    if key != "explanation":
        print(f"  {key:<25} {value}")
print()
print("EXPLANATION:")
print(scores.get("explanation", "N/A"))

=================================================================
POST ID: 10234810932441995  |  Date: 2025-08-14  |  Type: Photo
Engagement rate: 0.056  |  VTR: 0.834920634920635  |  Category: Algorithm Pushed

STRUCTURAL FEATURES:
  has_hashtag:       0  |  hashtag_count: 0
  has_tag:           N/A
  mentions_children: 1

FULL TEXT:
חופשה עם ילדים זאת מעין חצי חופשה.

לא מקבלים באמת את כל החופש שהיית רוצה ורוב הזמן את די עובדת, אבל כן יש רגעים קסומים.

כשדניאל קופץ וצוחק בבריכה. כשאני רואה איך לאט לאט נבנה לו הביטחון והוא לא מפחד יותר להיכנס ואפילו רוצה לקפוץ. כשאנחנו מלמדים אותו מזה קייט ופתאום הוא מחפש קייטים בים.

כשאני מביטה בקפלים המתוקים שברגליים השמנמנות שלו ומנסה לשתות כל רגע כזה לפני שהוא פשוט חולף.

כי למרות שכל ארוחה במסעדה היא סימפוניה של ״אני רוצה גם״ וכל נסיעה לים יכולה להסתיים בטנטרום כשרוצים כבר ללכת, אני כל הזמן מזכירה לעצמי שזה עוד רגע עובר והם כבר יהיו גדולים ואולי כבר לא יצטרכו אותי כל-כך.

כי הזמן יש בו משהו מתעתע. הוא נראה כאילו לעולם לא יגמר כשהוא בהתקף טנטרום אבל אז בן רגע הוא פתאם נהיה גדול וכבר לא התינוק הקטן והשמנמן שהחזקתי בידיים לפני רגע.

אז זאת מעין חצי חופשה כזאת שדורשת יותר עבודה סביב הילד אבל גם ממלאת אותי בו.

בתמונה - כלי הנשק הסודי שלי, גלידה.

LLM SCORES:
  emotional_valence         4
  emotional_intensity       3
  tone                      reflective
  marketing_mention         0
  occasion_mention          0
  occasion_relevance        0
  dominant_pronoun          I
  opening_pronoun           None
  question_presence         0
  list_structure            0
  narrative_arc             2
  personal_vulnerability    3
  parenthood_theme          1
  shared_context            1
  tag_count_people          0

EXPLANATION:
This is a highly vulnerable post in which the author exposes profound anxiety about the passage of time with her children—fear of being needed less, awareness of childhood's fleeting nature, and the emotional toll of motherhood. The raw emotional intensity comes through in her honest admission of parental ambivalence (not getting true rest, constant work) alongside deep love and presence. The post taps into a major shared life experience (the specific emotional journey of motherhood and watching children grow) and uses poignant sensory detail (dimples, chubby legs, ice cream) to ground her vulnerability in concrete memory.

## 6. Parse & Merge Results

Convert the checkpoint dictionary into a dataframe and merge with the
original clean dataset. Each score becomes a new column.

In [8]:
# Convert checkpoint to dataframe
scores_df = pd.DataFrame.from_dict(checkpoint, orient="index")
scores_df.index.name = "post_id"
scores_df = scores_df.reset_index()
scores_df["post_id"] = scores_df["post_id"].astype(df["post_id"].dtype)

print(f"Scores dataframe: {len(scores_df)} rows x {len(scores_df.columns)} columns")
print(f"Score columns: {[c for c in scores_df.columns if c != 'post_id']}")
scores_df.head(3)

Scores dataframe: 90 rows x 17 columns
Score columns: ['emotional_valence', 'emotional_intensity', 'tone', 'marketing_mention', 'occasion_mention', 'occasion_relevance', 'dominant_pronoun', 'opening_pronoun', 'question_presence', 'list_structure', 'narrative_arc', 'personal_vulnerability', 'parenthood_theme', 'shared_context', 'tag_count_people', 'explanation']

,post_id,emotional_valence,emotional_intensity,tone,marketing_mention,occasion_mention,occasion_relevance,dominant_pronoun,opening_pronoun,question_presence,list_structure,narrative_arc,personal_vulnerability,parenthood_theme,shared_context,tag_count_people,explanation
0,10234810932441995,4,3,reflective,0,1,2,I,None,0,0,2,3,1,1,0,This is a deeply vulnerable post where the aut...
1,10238066919799644,4,3,reflective,1,1,2,I,None,1,0,3,3,0,1,2,"This is a deeply personal, reflective post whe..."
2,10237996040547707,4,2,recommendation,0,0,0,I,We,1,0,2,2,0,0,0,This post is primarily a review/recommendation...

In [9]:
# Merge with clean dataset
df_enriched = df.merge(scores_df, on="post_id", how="left")

print(f"Enriched dataset: {len(df_enriched)} rows x {len(df_enriched.columns)} columns")
print(f"Posts with scores: {df_enriched['emotional_valence'].notna().sum()}")
print(f"Posts missing scores: {df_enriched['emotional_valence'].isna().sum()}")

Enriched dataset: 90 rows x 51 columns
Posts with scores: 90
Posts missing scores: 0

In [10]:
# Quick summary of score distributions
score_cols = [
    "emotional_valence", "emotional_intensity", "tone",
    "marketing_mention", "occasion_mention", "occasion_relevance",
    "dominant_pronoun", "opening_pronoun", "question_presence",
    "list_structure", "narrative_arc", "personal_vulnerability",
    "parenthood_theme",
    "shared_context",
    "tag_count_people"
]

print("Score distributions:")
print()
for col in score_cols:
    if col in df_enriched.columns:
        print(f"{col}:")
        print(df_enriched[col].value_counts().sort_index().to_string())
        print()

Score distributions:

emotional_valence:
emotional_valence
3     4
4    60
5    26

emotional_intensity:
emotional_intensity
1     3
2    38
3    49

tone:
tone
book_accomplishment    33
recommendation          9
reflective             48

marketing_mention:
marketing_mention
0    55
1    35

occasion_mention:
occasion_mention
0    65
1    25

occasion_relevance:
occasion_relevance
0    65
1     8
2     9
3     8

dominant_pronoun:
dominant_pronoun
I        74
Mixed     8
We        3
You       5

opening_pronoun:
opening_pronoun
I       25
None    62
We       2
You      1

question_presence:
question_presence
0    56
1    34

list_structure:
list_structure
0    70
1    20

narrative_arc:
narrative_arc
1    33
2    21
3    36

personal_vulnerability:
personal_vulnerability
1    27
2    20
3    43

parenthood_theme:
parenthood_theme
0    54
1    36

shared_context:
shared_context
0    36
1    54

tag_count_people:
tag_count_people
0     27
1     33
2     15
3      8
4      3
6      3
13     1

## 7. Export

Save the enriched dataset. This file is the input for `04_modeling.ipynb`.

In [11]:
OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
df_enriched.to_csv(OUTPUT_FILE, index=False, encoding="utf-8-sig")

print(f"✓ Exported {len(df_enriched)} posts to {OUTPUT_FILE}")
print(f"  Total columns: {len(df_enriched.columns)}")
print(f"  New text feature columns: {len(score_cols)}")

✓ Exported 90 posts to ../data/clean_posts_with_text.csv
  Total columns: 51
  New text feature columns: 15